name: Inject and Upload

on:
  workflow_dispatch:
    inputs:
      APOLLOURL:
        description: 'Direct URL to Apollo .ipa'
        required: true
      PATCHGLASS:
        description: 'Add Liquid Glass Patch (iOS 26)'
        required: false
        default: false
        type: boolean
      APOLLOREPO:
        description: 'Apollo-ImprovedCustomApi Repo'
        required: false
        default: "JeffreyCA/Apollo-ImprovedCustomApi"
      REDIRECTS:
        description: 'Custom redirect URIs, comma seperated'
        required: false
        
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up variables
      id: setup
      run: |
        echo "APOLLOURL=${{ github.event.inputs.APOLLOURL }}" >> $GITHUB_ENV
        echo "PATCHGLASS=${{ github.event.inputs.PATCHGLASS }}" >> $GITHUB_ENV
        GLASSREPO=$(echo "dankrichtofen/apolloliquidglass")
        echo "GLASSREPO=$GLASSREPO" >> $GITHUB_ENV
        echo "APOLLOREPO=${{ github.event.inputs.APOLLOREPO }}" >> $GITHUB_ENV
        echo "REDIRECTS=${{ github.event.inputs.REDIRECTS }}" >> $GITHUB_ENV
        echo "componentspath=Build Components" >> $GITHUB_ENV

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Cyan
      run: pipx install --force https://github.com/SpotCompiled/pyzule-rw/archive/main.zip
        
    - name: Create Build Components folder
      run: mkdir -p "Build Components"

    - name: Download Apollo IPA
      run: |
        echo "Downloading From: ${{ github.event.inputs.APOLLOURL }}"
        # Download the file using curl
        curl -LJO "${{ github.event.inputs.APOLLOURL }}"
        downloaded_file=$(ls -t | head -n1)
        mv "$downloaded_file" "Build Components/"
        echo "apollopath=Build Components/$downloaded_file" >> $GITHUB_ENV
      env:
        SPOTURL: ${{ github.event.inputs.APOLLOURL }}

    - name: Set APOLLOTAG
      run: |
        echo "APOLLOTAG not provided, fetching latest release tag..."
        APOLLOTAG=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ env.APOLLOREPO }}/releases/latest | jq -r .tag_name)
        echo "APOLLOTAG=$APOLLOTAG" >> $GITHUB_ENV
      env:
          APOLLOREPO: ${{ env.APOLLOREPO }}

    - name: Set GLASSTAG
      run: |
        echo "GLASSTAG not provided, fetching latest release tag..."
        GLASSTAG=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ env.GLASSREPO }}/releases/latest | jq -r .tag_name)
        echo "GLASSTAG=$GLASSTAG" >> $GITHUB_ENV
      env:
          GLASSREPO: ${{ env.GLASSREPO }}

    - name: Download ApolloPatcher .deb file from releases
      run: |
        apollo_asset=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ env.APOLLOREPO }}/releases/tags/${{ env.APOLLOTAG }} | jq -r '.assets[] | select(.name | startswith("ca.jeffrey.apollo-improvedcustomapi") and endswith("iphoneos-arm.deb")).browser_download_url')
        echo "Downloading From: $apollo_asset"
        # Download the file using curl
        curl -LJO "$apollo_asset"
        downloaded_file=$(ls -t | head -n1)
        mv "$downloaded_file" "Build Components/"
        echo "apollo-arm=Build Components/$downloaded_file" >> $GITHUB_ENV
      env:
        APOLLOREPO: ${{ env.APOLLOREPO }}
        APOLLOTAG: ${{ env.APOLLOTAG }}

    - name: Download GlassPatch .deb file from releases
      run: |
        glass_asset=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ env.GLASSREPO }}/releases/tags/${{ env.GLASSTAG }} | jq -r '.assets[] | select(.name | startswith("com.dankrichtofen.apollofix") and endswith("iphoneos-arm64.deb")).browser_download_url')
        echo "Downloading From: $glass_asset"
        # Download the file using curl
        curl -LJO "$glass_asset"
        downloaded_file=$(ls -t | head -n1)
        mv "$downloaded_file" "Build Components/"
        echo "glass-arm=Build Components/$downloaded_file" >> $GITHUB_ENV
      env:
        GLASSREPO: ${{ env.GLASSREPO }}
        GLASSTAG: ${{ env.GLASSTAG }}

    - name: Create plist to merge
      run: |
        plist_path="${{ env.componentspath }}/info.plist"
        
        # Start by creating the header for the plist
        echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > "$plist_path"
        echo "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">" >> "$plist_path"
        echo "<plist version=\"1.0\">" >> "$plist_path"
        echo "<dict>" >> "$plist_path"
        echo "  <key>CFBundleURLTypes</key>" >> "$plist_path"
        echo "  <array>" >> "$plist_path"
        echo "    <dict>" >> "$plist_path"
        echo "      <key>CFBundleURLSchemes</key>" >> "$plist_path"
        echo "      <array>" >> "$plist_path"
        
        # Split the REDIRECTS string
        IFS=',' read -ra SCHEMES <<< "${REDIRECTS}"
        apollo_exists=false
        
        for scheme in "${SCHEMES[@]}"; do
          echo "        <string>${scheme}</string>" >> "$plist_path"
          # Check if 'apollo' is in the list
          if [[ "$scheme" == "apollo" ]]; then
            apollo_exists=true
          fi
        done
        
        # Add "apollo" only if it wasn't found in the list
        if [[ "$apollo_exists" == false ]]; then
          echo "        <string>apollo</string>" >> "$plist_path"
        fi
          
        echo "      </array>" >> "$plist_path"
        echo "    </dict>" >> "$plist_path"
        echo "  </array>" >> "$plist_path"
        echo "</dict>" >> "$plist_path"
        echo "</plist>" >> "$plist_path"
      env:
        REDIRECTS: ${{ env.REDIRECTS }}
        componentspath: ${{ env.componentspath }}
      
    - name: Run Cyan
      run: |
        Cyan -i "${{ env.apollopath }}" -o "${{ env.componentspath }}/patched_apollo.ipa" -l "${{ env.componentspath }}/info.plist" -f "${{ env.apollo-arm }}" "${{ env.glass-arm }}" -u -w -gl
        echo "patchedapollo=${{ env.componentspath }}/patched_apollo.ipa"
        echo "patchedapollo=${{ env.componentspath }}/patched_apollo.ipa" >> $GITHUB_ENV
      env:
        apollopath: ${{ env.apollopath }}
        componentspath: ${{ env.componentspath }}
        apollo-arm: ${{ env.apollo-arm }}
        glass-arm: ${{ env.glass-arm }}
      
    - name: Upload to Catbox (Without Hash)
      run: |
        RELEASEURL=$(curl -F "reqtype=fileupload" -F "fileToUpload=@${{ env.patchedapollo }}" https://catbox.moe/user/api.php)
        echo "Standard Download URL: $RELEASEURL"
        echo "RELEASEURL=$RELEASEURL" >> $GITHUB_ENV
      env:
        patchedapollo: ${{ env.patchedapollo }}
